# Site settings
name: Derin Harekat
title: Derin Harekat
description: "niredharekat"
baseurl: ""
author: berkantkz
repository: DerinHarekat/derinharekat.github.io
#exclude: [""]

# Build settings
markdown: kramdown
permalinks: pretty
theme: jekyll-theme-leap-day